FROM python:3.10

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip

RUN pip install -r requirements.txt

COPY . .

CMD ["streamlit","run","app.py","--server.address=0.0.0.0","--server.port=8501"]